### PR TITLE
Uber plugins

### PR DESCRIPTION
**Pull request by malandrew**
This PR adds the following plugins as-is:

- TAPTestEngine
- ConfigurablePytestTestEngine
- ConfigurableGolangTestEngine
- ArcanistLintTrapLinter (will be deprecated in the future, but valid for now)
- ArcanistUberStandardLinter

Refactoring to DRY up these plugins can be accomplished in a future pull request.

### CODE REVIEW

**Comment by malandrew** [comment]
Installation on devserver to try this out:

```bash
cd ~
git clone git@github.com:uber/arcanist.git
git clone git@github.com:uber/libphutil.git
ARCPATH=`which arc`
sudo rm $ARCPATH
sudo ln -s `pwd`/arcanist/bin/arc $ARCPATH
cd ~/arcanist
git checkout uber-plugins
```

I verified that ArcanistLintTrapLinter and TAPTestEngine worked correctly.

**Comment by sectioneight** [comment]
Can you try running `arc unit` on the go-common repo?

**Comment by malandrew** [comment]
will do

**Comment by malandrew** [comment]
ConfigurablePytestTestEngine tested and working. Waiting for puppet to finish running so I have a GOPATH, then I will check go.

**Comment by sectioneight** [comment]
:+1: from me then. we can follow up and DRY the unit engines in another pass.

**Comment by malandrew** [comment]
Renamed the uber-standard and lint-trap linters back to their original names for now. The reason for this is that arcanist will complain if two different lint classes attempt to use the same namespace. Rolling it out with a different name will break the build for everything that `loads` the old version with a different name. Loading with the same name will silently override. Once all projects have updated their `.arcconfig` and deleted either `.arcanist/` or uber-dot-arcanist from their package.json, we can look into renaming the linters for consistency like I had originally planned.

**Comment by malandrew** [comment]
@sectioneight yup, it works with the go test engine. fwiw, there is an error with those tests(`cannot find package "github.com/getsentry/raven-go"`), but that error existed even on the current version of arc with the embedded version of the golang test engine

**Comment by sectioneight** [comment]
Well, it's not an error in the test, it just means you didn't follow the readme :P (a `godep restore`) will fix it

**Comment by malandrew** [comment]
Anyways, can I merge this now that we've confirmed that it works for all the plugins?

**Comment by sectioneight** [comment]
cool with me

**Pull request merged**
