### PR TITLE
Add UberMavenTestEngine

### PR DESCRIPTION
**Pull request by JohnieLee**
Add Maven unit test engine to support maven tests for `arc unit`

Add the following to .arcconfig to enable

```
    "unit.engine": "MavenTestEngine",
    "unit.engine.command": "mvn test "
```

### CODE REVIEW

**Comment by andrewdeandrade** [comment]
Have you tested this locally?

**Comment by andrewdeandrade** [comment]
Also, can you add documentation on usage in a comment block at the top of the plugin.

**Comment by JohnieLee** [comment]
Yup, I have tested it locally:

```
$ arc unit
Running unit tests...
    `mvn test `

   PASS  524ms   com.uber.money.app.common.thrift.XTChannelServiceLifecycleTest.testDoStart
   PASS    1ms★  com.uber.money.app.common.thrift.XTChannelServiceLifecycleTest.testDoStop
```

**Comment by andrewdeandrade** [comment]
LGTM. Ship it.

**Pull request merged**
