### PR TITLE
Fix undefined offset

### PR DESCRIPTION
**Pull request by jessespears**
# Overview

This mitigates an issue that is caused by commit metadata being interpreted as revision ids, and then an array is incorrectly dereferenced, causing `arc diff` to fail.

This only fixes the symptom. The root cause of invalid revision ids being gathered needs to be fixed.

# Reproduction instructions

1. Create a diff with `arc diff`.

2. Reset your local branch and `arc patch $NAME_OF_YOUR_DIFF_REVISION`.

3. Perform a change and commit it.

4. `arc diff` again. This should fail with the following error: `ERROR 8: Undefined offset: $NUMERIC_PORTION_OF_YOUR_DIFF_REVISION`

# When bug was introduced

It was introduced when support for the `arc stack` command was included: 0e5599a106997d5754c691eedcce884736c99788

### CODE REVIEW

**Comment by mindaugasrukas** [comment]
LGTM

**Comment by mindaugasrukas** [comment]
Can we introduce this to the upstream?

**Comment by robbertvanginkel** [comment]
Any movement on this? I see some people filing issues on this internally.

> Can we introduce this to the upstream?
It seems like the bug was introduced in the fork, so I don't think we can upstream?

**Comment by gonix** [comment]
@bvaradar could you review the changes in this PR since you introduced the code in question?

**Comment by bvaradar** [comment]
Thanks. Looks Good.

**Pull request merged**
