### PR TITLE
Add GoFmt linter

### PR DESCRIPTION
**Pull request by sectioneight**
Summary:
Unlike GoLint or GoVet, Gofmt formats Go programs. It uses tabs (width= 8) for indentation and blanks for alignment.

Refs T6867

Test Plan: All of the unit tests are derived from real Go files that were formatted by gofmt.

Reviewers: #blessed_reviewers

Subscribers: ryansking, ox, epriestley, joshuaspence, sectioneight

Maniphest Tasks: T6867

Differential Revision: https://secure.phabricator.com/D12620

### CODE REVIEW

**Comment by sectioneight** [comment]
image

**Comment by sectioneight** [comment]
@breerly or somebody to review?

**Comment by danqing** [comment]
LGTM o.O

**Comment by Robpol86** [comment]
lgtm

**Pull request merged**
